name:                pancakesorting
version:             0.1.0.0
github:              "20970595/pancakesorting"
license:             BSD3
author:              "Mompati Erold Keetile"
maintainer:          "20970595@sun.ac.za"
copyright:           "2021 All rights reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Assignment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Patco-Erold/pancakesorting#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pancakesorting-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pancakesorting

tests:
  pancakesorting-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pancakesorting
    - hspec
    - QuickCheck
